export const mockIdoso = {
  id: '1',
  nome: 'José Silva',
  email: 'jose.silva@email.com',
  telefone: '(11) 99999-1234',
  endereco: 'Rua das Flores, 123 - Centro',
  dataNascimento: '1950-05-15',
  fotoPerfil: 'https://images.unsplash.com/photo-1566616213894-2d4e1baee5d8?w=200&h=200&fit=crop&crop=face',
  tipo: 'idoso',
  acessibilidades: ['motora'],
  contatosConfianca: [
    { id: '1', nome: 'Maria Silva', telefone: '(11) 98888-1234', relacao: 'Filha' },
    { id: '2', nome: 'Carlos Silva', telefone: '(11) 97777-1234', relacao: 'Filho' },
  ],
};

export const mockVoluntario = {
  id: '2',
  nome: 'Ana Santos',
  email: 'ana.santos@email.com',
  telefone: '(11) 99999-5678',
  endereco: 'Av. Paulista, 1000 - Bela Vista',
  dataNascimento: '1990-08-20',
  fotoPerfil: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop&crop=face',
  tipo: 'voluntario',
  disponibilidade: ['manha', 'tarde'],
  avaliacao: 4.9,
  totalAjudas: 24,
};

export const mockRequests = [
  {
    id: '1',
    idosoId: '1',
    idosoNome: 'José Silva',
    voluntarioId: '2',
    voluntarioNome: 'Ana Santos',
    titulo: 'Compras no mercado',
    descricao: 'Preciso de ajuda para fazer compras no mercado. Lista com aproximadamente 15 itens.',
    categoria: 'compras',
    urgencia: 'media',
    status: 'em_progresso',
    localizacao: 'Centro',
    distancia: '1.2 km',
    dataCriacao: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    dataAtualizacao: new Date().toISOString(),
  },
  {
    id: '2',
    idosoId: '1',
    idosoNome: 'José Silva',
    titulo: 'Conserto de torneira',
    descricao: 'A torneira da cozinha está vazando e preciso de alguém para consertar.',
    categoria: 'consertos',
    urgencia: 'alta',
    status: 'aberto',
    localizacao: 'Centro',
    distancia: '1.2 km',
    dataCriacao: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    dataAtualizacao: new Date().toISOString(),
  },
  {
    id: '3',
    idosoId: '1',
    idosoNome: 'José Silva',
    voluntarioId: '2',
    voluntarioNome: 'Ana Santos',
    titulo: 'Passeio no parque',
    descricao: 'Gostaria de companhia para um passeio no parque perto de casa.',
    categoria: 'companhia',
    urgencia: 'baixa',
    status: 'concluido',
    localizacao: 'Centro',
    distancia: '1.2 km',
    dataCriacao: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    dataAtualizacao: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '4',
    idosoId: '3',
    idosoNome: 'Maria Oliveira',
    titulo: 'Ajuda com medicamentos',
    descricao: 'Preciso buscar medicamentos na farmácia. São 3 remédios de uso contínuo.',
    categoria: 'compras',
    urgencia: 'alta',
    status: 'aberto',
    localizacao: 'Jardins',
    distancia: '800 m',
    dataCriacao: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    dataAtualizacao: new Date().toISOString(),
  },
  {
    id: '5',
    idosoId: '4',
    idosoNome: 'Pedro Costa',
    titulo: 'Troca de lâmpada',
    descricao: 'A lâmpada da sala queimou e não consigo trocar sozinho.',
    categoria: 'reparos',
    urgencia: 'baixa',
    status: 'aberto',
    localizacao: 'Vila Madalena',
    distancia: '2.5 km',
    dataCriacao: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    dataAtualizacao: new Date().toISOString(),
  },
];

export const mockNearbyVolunteers = [
  {
    id: '2',
    nome: 'Ana Santos',
    fotoPerfil: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop&crop=face',
    distancia: '500 m',
  },
  {
    id: '5',
    nome: 'Lucas Pereira',
    fotoPerfil: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face',
    distancia: '1.2 km',
  },
  {
    id: '6',
    nome: 'Mariana Lima',
    fotoPerfil: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop&crop=face',
    distancia: '1.8 km',
  },
  {
    id: '7',
    nome: 'Rafael Souza',
    fotoPerfil: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop&crop=face',
    distancia: '2.3 km',
  },
];

export const mockNearbyIdosos = [
  {
    id: '1',
    nome: 'José Silva',
    fotoPerfil: 'https://images.unsplash.com/photo-1566616213894-2d4e1baee5d8?w=200&h=200&fit=crop&crop=face',
    distancia: '800 m',
  },
  {
    id: '3',
    nome: 'Maria Oliveira',
    fotoPerfil: 'https://images.unsplash.com/photo-1581579438747-1dc8d17bbce4?w=200&h=200&fit=crop&crop=face',
    distancia: '1.5 km',
  },
  {
    id: '4',
    nome: 'Pedro Costa',
    fotoPerfil: 'https://images.unsplash.com/photo-1559963110-71b394e7494d?w=200&h=200&fit=crop&crop=face',
    distancia: '2.1 km',
  },
];